name: Auto-Sync Upstream
on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 mins
#    - cron: '0 6 * * *' # Runs daily at 6 AM UTC
  workflow_dispatch:    # Allows manual trigger from the Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout fork
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Required for proper merging

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch and Merge Upstream
        run: |
          git remote add upstream https://github.com/rooted-graphene/ota.git
          git fetch upstream
          git merge upstream/main --no-edit -m "chore: sync upstream $(date +%Y-%m-%d)"
          git push origin main
